### ISSUE TITLE
set content type to application/json

### ISSUE THREAD

**Issue by terravibe** [fulls1z3/ngx-auth#42]
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Support request => 
[x ] Feature request
[ ] Documentation issue or request

Hey!

As i see, the authentication is posting the data with 'content-type:text/plain'.
Is there any option to send the post request with content type: application/json?

**Comment by fulls1z3** [comment]
@terravibe that's really a good point, added this feature to our roadmap and soon see what can we do about it.

**Comment by fulls1z3** [comment]
@terravibe introduced the `HttpClient` of Angular 5. Check these features, probably it should work.

**Comment by abdekalder** [comment]
I have version 5.1.0 and still is 'Content-type: text/plain' - how can I change to 'Content-type: application/json'? Thank you

**Comment by abdekalder** [comment]
My endpoint returns json object like this { id_token : "token" } this package needed token = res && res.token, how can I map to my custom json object?

**Comment by chrisworrell** [comment]
@abdekalder To get around this you can easily just implement an HTTP_INTERCEPTOR.

I just did the same thing (as well as modify the username on the request to be email instead) and modified the response as well to change id to token.

```
import { Injectable, Injector } from '@angular/core';
import { HttpEvent, HttpHandler, HttpInterceptor, HttpRequest, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs/Rx';
import 'rxjs/add/observable/throw';
import 'rxjs/add/operator/catch';

@Injectable()
export class ZfHttpInterceptor implements HttpInterceptor {
    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        if (req.url === '{{LOGIN_URL}}' && req.method === 'POST') {
            const updatedRequest = req.clone({
                body: req.body.replace(/username/gi, 'email'),
                setHeaders: {
                    'Content-Type': 'application/json'
                }
            });

            return next
                .handle(updatedRequest)
                .map(event => {
                    if (event instanceof HttpResponse)
                        event = event.clone({ body: {token: event.body.id} });

                    return event;
                })
                .catch((error, caught) => {
                    return Observable.throw(error);
                }) as any;
        } else {
            return next.handle(req)
                .catch((error, caught) => {
                    return Observable.throw(error);
                }) as any;
        }
    }
}


```
